#!/usr/bin/env bash

browser="brave"

$browser --new-window\
    https://github.com/AURA-AI-FR \
    https://console.cloud.google.com \
    https://console.firebase.google.com/project/aura-32937/overview \
    https://n8n.aura-ai.fr/home/workflows &
